management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include:
            - db
            - readinessState
        liveness:
          include:
            - livenessState
      status:
        order: DOWN, OUT_OF_SERVICE, DEGRADED, UP, UNKNOWN
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

spring:
  application:
    name: billing
  cloud:
    circuitbreaker:
      http-services:
        enabled: false
  flyway:
    enabled: false
  http:
    clients:
      imperative:
        factory: http_components
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  web:
    locale-resolver: fixed
    locale: en_US

algashop:
  integrations:
    payment:
      provider: FASTPAY

resilience4j:
  circuitbreaker:
    instances:
      fastpayCB:
        register-health-indicator: true
        sliding-window-type: time_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - br.dev.allissonnunes.algashop.billing.infrastructure.exception.BadGatewayException.ClientErrorException
  timelimiter:
    instances:
      fastpayCB:
        timeoutDuration: 20s
  retry:
    instances:
      fastpayRetry:
        max-attempts: 3
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2.0
        wait-duration: 3s
        retry-exceptions:
          - br.dev.allissonnunes.algashop.billing.infrastructure.exception.BadGatewayException.ServerErrorException
          - br.dev.allissonnunes.algashop.billing.infrastructure.exception.GatewayTimeoutException